//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BindingProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BindingProject.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ↺ Сбросить к значениям по умолчанию.
        /// </summary>
        internal static string Button_DefaultBinding_ResetToDefault {
            get {
                return ResourceManager.GetString("Button_DefaultBinding_ResetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить.
        /// </summary>
        internal static string Button_OneTime_ResetAll {
            get {
                return ResourceManager.GetString("Button_OneTime_ResetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить &apos;Ноутбук&apos;.
        /// </summary>
        internal static string Button_OneTime_SetLaptop {
            get {
                return ResourceManager.GetString("Button_OneTime_SetLaptop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить &apos;Телефон&apos;.
        /// </summary>
        internal static string Button_OneTime_SetPhone {
            get {
                return ResourceManager.GetString("Button_OneTime_SetPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс.
        /// </summary>
        internal static string Button_Reset {
            get {
                return ResourceManager.GetString("Button_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Установить цену 99999.
        /// </summary>
        internal static string Button_SetHighPrice {
            get {
                return ResourceManager.GetString("Button_SetHighPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноутбук.
        /// </summary>
        internal static string Button_SetLaptop {
            get {
                return ResourceManager.GetString("Button_SetLaptop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        internal static string Button_SetPhone {
            get {
                return ResourceManager.GetString("Button_SetPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена 25000.
        /// </summary>
        internal static string Button_SetPrice25000 {
            get {
                return ResourceManager.GetString("Button_SetPrice25000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена 50000.
        /// </summary>
        internal static string Button_SetPrice50000 {
            get {
                return ResourceManager.GetString("Button_SetPrice50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена 75000.
        /// </summary>
        internal static string Button_SetPrice75000 {
            get {
                return ResourceManager.GetString("Button_SetPrice75000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить название на &apos;Новый товар&apos;.
        /// </summary>
        internal static string Button_TwoWay_ResetNameToNewProduct {
            get {
                return ResourceManager.GetString("Button_TwoWay_ResetNameToNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на рублей.
        /// </summary>
        internal static string Currency_RublesLong {
            get {
                return ResourceManager.GetString("Currency_RublesLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на руб.
        /// </summary>
        internal static string Currency_RublesShort {
            get {
                return ResourceManager.GetString("Currency_RublesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении текста в полях и потере фокуса - обновляется блок отображения.
        /// </summary>
        internal static string DefaultBindingView_Bullet1 {
            get {
                return ResourceManager.GetString("DefaultBindingView_Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИТОГО обновляется автоматически при изменении цены или количества.
        /// </summary>
        internal static string DefaultBindingView_Bullet2 {
            get {
                return ResourceManager.GetString("DefaultBindingView_Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UpdateSourceTrigger=PropertyChanged - обновление после каждого символа.
        /// </summary>
        internal static string DefaultBindingView_Bullet3 {
            get {
                return ResourceManager.GetString("DefaultBindingView_Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Default привязка: WPF сам выбирает режим. Для TextBox это TwoWay (при потере фокуса), для TextBlock это OneWay..
        /// </summary>
        internal static string DefaultBindingView_Description {
            get {
                return ResourceManager.GetString("DefaultBindingView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✏️ Разница: во втором поле изменения видны сразу в блоке отображения выше.
        /// </summary>
        internal static string DefaultBindingView_DifferenceText {
            get {
                return ResourceManager.GetString("DefaultBindingView_DifferenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 👁️ Отображение данных (TextBlock с OneWay).
        /// </summary>
        internal static string DefaultBindingView_DisplayDataTitle {
            get {
                return ResourceManager.GetString("DefaultBindingView_DisplayDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✏️ Редактируемые поля (TextBox).
        /// </summary>
        internal static string DefaultBindingView_EditableFieldsTitle {
            get {
                return ResourceManager.GetString("DefaultBindingView_EditableFieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычный TextBox (обновление при потере фокуса):.
        /// </summary>
        internal static string DefaultBindingView_NormalTextBoxLabel {
            get {
                return ResourceManager.GetString("DefaultBindingView_NormalTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox с PropertyChanged (обновление после каждой буквы):.
        /// </summary>
        internal static string DefaultBindingView_PropertyChangedTextBoxLabel {
            get {
                return ResourceManager.GetString("DefaultBindingView_PropertyChangedTextBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔹 Привязка по умолчанию (Default).
        /// </summary>
        internal static string DefaultBindingView_Title {
            get {
                return ResourceManager.GetString("DefaultBindingView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚡ Демонстрация UpdateSourceTrigger.
        /// </summary>
        internal static string DefaultBindingView_UpdateSourceTriggerDemoTitle {
            get {
                return ResourceManager.GetString("DefaultBindingView_UpdateSourceTriggerDemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 Что демонстрирует привязка Default:.
        /// </summary>
        internal static string DefaultBindingView_WhatDefaultShowsLabel {
            get {
                return ResourceManager.GetString("DefaultBindingView_WhatDefaultShowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последнее изменение:.
        /// </summary>
        internal static string Label_LastUpdateTime {
            get {
                return ResourceManager.GetString("Label_LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название:.
        /// </summary>
        internal static string Label_NameColon {
            get {
                return ResourceManager.GetString("Label_NameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название (OneTime):.
        /// </summary>
        internal static string Label_NameOneTimeColon {
            get {
                return ResourceManager.GetString("Label_NameOneTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена:.
        /// </summary>
        internal static string Label_PriceColon {
            get {
                return ResourceManager.GetString("Label_PriceColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена (OneTime):.
        /// </summary>
        internal static string Label_PriceOneTimeColon {
            get {
                return ResourceManager.GetString("Label_PriceOneTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена (руб):.
        /// </summary>
        internal static string Label_PriceRubColon {
            get {
                return ResourceManager.GetString("Label_PriceRubColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прогресс цены:.
        /// </summary>
        internal static string Label_ProgressPrice {
            get {
                return ResourceManager.GetString("Label_ProgressPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество:.
        /// </summary>
        internal static string Label_QuantityColon {
            get {
                return ResourceManager.GetString("Label_QuantityColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество (OneTime):.
        /// </summary>
        internal static string Label_QuantityOneTimeColon {
            get {
                return ResourceManager.GetString("Label_QuantityOneTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИТОГО:.
        /// </summary>
        internal static string Label_TotalAllCapsColon {
            get {
                return ResourceManager.GetString("Label_TotalAllCapsColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого:.
        /// </summary>
        internal static string Label_TotalColon {
            get {
                return ResourceManager.GetString("Label_TotalColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого (OneTime):.
        /// </summary>
        internal static string Label_TotalOneTimeColon {
            get {
                return ResourceManager.GetString("Label_TotalOneTimeColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        internal static string Language_English {
            get {
                return ResourceManager.GetString("Language_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string Language_Russian {
            get {
                return ResourceManager.GetString("Language_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Локализация WPF.
        /// </summary>
        internal static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена изменена на {0} рублей.
        /// </summary>
        internal static string Message_PriceChanged {
            get {
                return ResourceManager.GetString("Message_PriceChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажимай кнопки, двигай слайдер - правая колонка остается неизменной.
        /// </summary>
        internal static string OneTimeBindingView_Bullet_KeepRightColumnUnchanged {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Bullet_KeepRightColumnUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Левая колонка (TwoWay) - данные обновляются при любых изменениях.
        /// </summary>
        internal static string OneTimeBindingView_Bullet_LeftColumn {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Bullet_LeftColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правая колонка (OneTime) - застыла при загрузке и не меняется.
        /// </summary>
        internal static string OneTimeBindingView_Bullet_RightColumnFixed {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Bullet_RightColumnFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📝 Вывод: OneTime привязка берет значение модели один раз при загрузке и больше не обновляется, даже если модель меняется.
        /// </summary>
        internal static string OneTimeBindingView_Conclusion {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка обновляет интерфейс .
        /// </summary>
        internal static string OneTimeBindingView_DescPart1 {
            get {
                return ResourceManager.GetString("OneTimeBindingView_DescPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на только один раз.
        /// </summary>
        internal static string OneTimeBindingView_DescPart2 {
            get {
                return ResourceManager.GetString("OneTimeBindingView_DescPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на при загрузке. Дальнейшие изменения данных .
        /// </summary>
        internal static string OneTimeBindingView_DescPart3 {
            get {
                return ResourceManager.GetString("OneTimeBindingView_DescPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на не обновляют.
        /// </summary>
        internal static string OneTimeBindingView_DescPart4 {
            get {
                return ResourceManager.GetString("OneTimeBindingView_DescPart4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на интерфейс, даже если модель оповещает об изменениях..
        /// </summary>
        internal static string OneTimeBindingView_DescPart5 {
            get {
                return ResourceManager.GetString("OneTimeBindingView_DescPart5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 ПРИМЕР 1: OneTime привязка (не обновляется).
        /// </summary>
        internal static string OneTimeBindingView_Example1_Title {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Example1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 Что демонстрирует OneTime привязка:.
        /// </summary>
        internal static string OneTimeBindingView_ExplanationTitle {
            get {
                return ResourceManager.GetString("OneTimeBindingView_ExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактируемые поля (TwoWay).
        /// </summary>
        internal static string OneTimeBindingView_Header_Editor {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Header_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime привязка (не меняется).
        /// </summary>
        internal static string OneTimeBindingView_Header_OneTimeFixed {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Header_OneTimeFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена: .
        /// </summary>
        internal static string OneTimeBindingView_PriceLabel {
            get {
                return ResourceManager.GetString("OneTimeBindingView_PriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 Изменяем данные в коде.
        /// </summary>
        internal static string OneTimeBindingView_Section_ChangeDataInCode {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Section_ChangeDataInCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎚️ Слайдер меняет цену (TwoWay).
        /// </summary>
        internal static string OneTimeBindingView_SliderDemoTitle {
            get {
                return ResourceManager.GetString("OneTimeBindingView_SliderDemoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⏱️ Одноразовая привязка (OneTime).
        /// </summary>
        internal static string OneTimeBindingView_Title {
            get {
                return ResourceManager.GetString("OneTimeBindingView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWay элементы показывают данные, но не могут их изменить.
        /// </summary>
        internal static string OneWayBindingView_Bullet1 {
            get {
                return ResourceManager.GetString("OneWayBindingView_Bullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении модели все OneWay элементы обновляются автоматически.
        /// </summary>
        internal static string OneWayBindingView_Bullet2 {
            get {
                return ResourceManager.GetString("OneWayBindingView_Bullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Идеально для отображения информации, статистики, прогресса.
        /// </summary>
        internal static string OneWayBindingView_Bullet3 {
            get {
                return ResourceManager.GetString("OneWayBindingView_Bullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В отличие от OneTime, OneWay продолжает следить за изменениями.
        /// </summary>
        internal static string OneWayBindingView_Bullet4 {
            get {
                return ResourceManager.GetString("OneWayBindingView_Bullet4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор (TwoWay).
        /// </summary>
        internal static string OneWayBindingView_CompareGrid_Header_Editor {
            get {
                return ResourceManager.GetString("OneWayBindingView_CompareGrid_Header_Editor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneTime (застыл).
        /// </summary>
        internal static string OneWayBindingView_CompareGrid_Header_OneTime {
            get {
                return ResourceManager.GetString("OneWayBindingView_CompareGrid_Header_OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWay (обновляется).
        /// </summary>
        internal static string OneWayBindingView_CompareGrid_Header_OneWay {
            get {
                return ResourceManager.GetString("OneWayBindingView_CompareGrid_Header_OneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляй ценой через слайдер:.
        /// </summary>
        internal static string OneWayBindingView_ControlSliderLabel {
            get {
                return ResourceManager.GetString("OneWayBindingView_ControlSliderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая цена: .
        /// </summary>
        internal static string OneWayBindingView_CurrentPriceLabel {
            get {
                return ResourceManager.GetString("OneWayBindingView_CurrentPriceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OneWay привязка: данные текут.
        /// </summary>
        internal static string OneWayBindingView_DescPart1 {
            get {
                return ResourceManager.GetString("OneWayBindingView_DescPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на только из модели в интерфейс.
        /// </summary>
        internal static string OneWayBindingView_DescPart2 {
            get {
                return ResourceManager.GetString("OneWayBindingView_DescPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . Пользователь может видеть данные, но не может их изменить через этот элемент..
        /// </summary>
        internal static string OneWayBindingView_DescPart3 {
            get {
                return ResourceManager.GetString("OneWayBindingView_DescPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 ПРИМЕР 1: TextBlock с OneWay (только просмотр).
        /// </summary>
        internal static string OneWayBindingView_Example1_Title {
            get {
                return ResourceManager.GetString("OneWayBindingView_Example1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📊 ПРИМЕР 2: Визуальные элементы с OneWay.
        /// </summary>
        internal static string OneWayBindingView_Example2_Title {
            get {
                return ResourceManager.GetString("OneWayBindingView_Example2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎚️ ПРИМЕР 3: Слайдер (TwoWay) и индикаторы (OneWay).
        /// </summary>
        internal static string OneWayBindingView_Example3_Title {
            get {
                return ResourceManager.GetString("OneWayBindingView_Example3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 ПРИМЕР 4: OneWay vs OneTime (наглядное сравнение).
        /// </summary>
        internal static string OneWayBindingView_Example4_Title {
            get {
                return ResourceManager.GetString("OneWayBindingView_Example4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 Что демонстрирует OneWay привязка:.
        /// </summary>
        internal static string OneWayBindingView_ExplanationTitle {
            get {
                return ResourceManager.GetString("OneWayBindingView_ExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование (TwoWay).
        /// </summary>
        internal static string OneWayBindingView_Header_EditTwoWay {
            get {
                return ResourceManager.GetString("OneWayBindingView_Header_EditTwoWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотр (OneWay).
        /// </summary>
        internal static string OneWayBindingView_Header_ViewOneWay {
            get {
                return ResourceManager.GetString("OneWayBindingView_Header_ViewOneWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название товара: .
        /// </summary>
        internal static string OneWayBindingView_ProductNameLabel {
            get {
                return ResourceManager.GetString("OneWayBindingView_ProductNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🎮 Тестовые кнопки (меняют данные в модели).
        /// </summary>
        internal static string OneWayBindingView_TestButtonsTitle {
            get {
                return ResourceManager.GetString("OneWayBindingView_TestButtonsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ➡️ Односторонние привязки (OneWay).
        /// </summary>
        internal static string OneWayBindingView_Title {
            get {
                return ResourceManager.GetString("OneWayBindingView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        internal static string Product_Price {
            get {
                return ResourceManager.GetString("Product_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество.
        /// </summary>
        internal static string Product_Quantity {
            get {
                return ResourceManager.GetString("Product_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итого.
        /// </summary>
        internal static string Product_Total {
            get {
                return ResourceManager.GetString("Product_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        internal static string ProductName_Default {
            get {
                return ResourceManager.GetString("ProductName_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноутбук.
        /// </summary>
        internal static string ProductName_Laptop {
            get {
                return ResourceManager.GetString("ProductName_Laptop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноутбук ASUS.
        /// </summary>
        internal static string ProductName_LaptopASUS {
            get {
                return ResourceManager.GetString("ProductName_LaptopASUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый товар.
        /// </summary>
        internal static string ProductName_NewProduct {
            get {
                return ResourceManager.GetString("ProductName_NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смартфон.
        /// </summary>
        internal static string ProductName_Phone {
            get {
                return ResourceManager.GetString("ProductName_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смартфон Samsung.
        /// </summary>
        internal static string ProductName_PhoneSamsung {
            get {
                return ResourceManager.GetString("ProductName_PhoneSamsung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Привязка по умолчанию.
        /// </summary>
        internal static string Tab_DefaultBinding {
            get {
                return ResourceManager.GetString("Tab_DefaultBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одноразовая привязка.
        /// </summary>
        internal static string Tab_OneTimeBinding {
            get {
                return ResourceManager.GetString("Tab_OneTimeBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Односторонние привязки.
        /// </summary>
        internal static string Tab_OneWayBinding {
            get {
                return ResourceManager.GetString("Tab_OneWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры.
        /// </summary>
        internal static string Tab_Triggers {
            get {
                return ResourceManager.GetString("Tab_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двухсторонняя привязка.
        /// </summary>
        internal static string Tab_TwoWayBinding {
            get {
                return ResourceManager.GetString("Tab_TwoWayBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажми меня.
        /// </summary>
        internal static string Triggers_Button_ClickMe {
            get {
                return ResourceManager.GetString("Triggers_Button_ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наведи мышку.
        /// </summary>
        internal static string Triggers_Button_HoverMouse {
            get {
                return ResourceManager.GetString("Triggers_Button_HoverMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есть промокод.
        /// </summary>
        internal static string Triggers_CheckBox_HasPromoCode {
            get {
                return ResourceManager.GetString("Triggers_CheckBox_HasPromoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Праздничный день.
        /// </summary>
        internal static string Triggers_CheckBox_IsHoliday {
            get {
                return ResourceManager.GetString("Triggers_CheckBox_IsHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отметь меня.
        /// </summary>
        internal static string Triggers_CheckBox_MarkMe {
            get {
                return ResourceManager.GetString("Triggers_CheckBox_MarkMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Постоянный клиент.
        /// </summary>
        internal static string Triggers_CheckBox_RegularCustomer {
            get {
                return ResourceManager.GetString("Triggers_CheckBox_RegularCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Условия для скидки:.
        /// </summary>
        internal static string Triggers_Discount_ConditionsLabel {
            get {
                return ResourceManager.GetString("Triggers_Discount_ConditionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваша скидка:.
        /// </summary>
        internal static string Triggers_MyDiscountLabel {
            get {
                return ResourceManager.GetString("Triggers_MyDiscountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена.
        /// </summary>
        internal static string Triggers_Table_Header_Price {
            get {
                return ResourceManager.GetString("Triggers_Table_Header_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        internal static string Triggers_Table_Header_Product {
            get {
                return ResourceManager.GetString("Triggers_Table_Header_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        internal static string Triggers_Table_Header_Quantity {
            get {
                return ResourceManager.GetString("Triggers_Table_Header_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string Triggers_Table_Header_Status {
            get {
                return ResourceManager.GetString("Triggers_Table_Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при изменении данных в модели (привязка к свойству).
        /// </summary>
        internal static string TriggersView_DataTriggerExplanation {
            get {
                return ResourceManager.GetString("TriggersView_DataTriggerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔹 2. DataTrigger (привязка к данным).
        /// </summary>
        internal static string TriggersView_DataTriggerTitle {
            get {
                return ResourceManager.GetString("TriggersView_DataTriggerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✓ При клике: мигает и сжимается.
        /// </summary>
        internal static string TriggersView_EventExample1_Hint {
            get {
                return ResourceManager.GetString("TriggersView_EventExample1_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кнопка с анимацией при клике.
        /// </summary>
        internal static string TriggersView_EventExample1_Title {
            get {
                return ResourceManager.GetString("TriggersView_EventExample1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анимация при наведении.
        /// </summary>
        internal static string TriggersView_EventExample2_Title {
            get {
                return ResourceManager.GetString("TriggersView_EventExample2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚡ Триггеры в действии ⚡.
        /// </summary>
        internal static string TriggersView_EventExample3_LargeTitle {
            get {
                return ResourceManager.GetString("TriggersView_EventExample3_LargeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анимация при загрузке.
        /// </summary>
        internal static string TriggersView_EventExample3_Title {
            get {
                return ResourceManager.GetString("TriggersView_EventExample3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при возникновении события (Click, Loaded, MouseEnter) и запускает анимацию.
        /// </summary>
        internal static string TriggersView_EventTriggerExplanation {
            get {
                return ResourceManager.GetString("TriggersView_EventTriggerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔹 3. EventTrigger (события и анимация).
        /// </summary>
        internal static string TriggersView_EventTriggerTitle {
            get {
                return ResourceManager.GetString("TriggersView_EventTriggerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✓ IsMouseOver: меняет цвет, размер, шрифт.
        /// </summary>
        internal static string TriggersView_Example1_Hint {
            get {
                return ResourceManager.GetString("TriggersView_Example1_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кнопка с триггером на наведение.
        /// </summary>
        internal static string TriggersView_Example1_Title {
            get {
                return ResourceManager.GetString("TriggersView_Example1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет фона меняется при отметке.
        /// </summary>
        internal static string TriggersView_Example2_Hint {
            get {
                return ResourceManager.GetString("TriggersView_Example2_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CheckBox с триггером на IsChecked.
        /// </summary>
        internal static string TriggersView_Example2_Title {
            get {
                return ResourceManager.GetString("TriggersView_Example2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ✓ При фокусе: синяя рамка, голубой фон.
        /// </summary>
        internal static string TriggersView_Example3_Hint {
            get {
                return ResourceManager.GetString("TriggersView_Example3_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TextBox с триггером на IsFocused.
        /// </summary>
        internal static string TriggersView_Example3_Title {
            get {
                return ResourceManager.GetString("TriggersView_Example3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывают при выполнении нескольких условий одновременно.
        /// </summary>
        internal static string TriggersView_MultiTriggerExplanation {
            get {
                return ResourceManager.GetString("TriggersView_MultiTriggerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔹 4. MultiTrigger и MultiDataTrigger (несколько условий).
        /// </summary>
        internal static string TriggersView_MultiTriggerTitle {
            get {
                return ResourceManager.GetString("TriggersView_MultiTriggerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при изменении свойства самого элемента (IsMouseOver, IsFocused, IsChecked).
        /// </summary>
        internal static string TriggersView_PropertyTriggerExplanation {
            get {
                return ResourceManager.GetString("TriggersView_PropertyTriggerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔹 1. PropertyTrigger (свойство элемента).
        /// </summary>
        internal static string TriggersView_PropertyTriggerTitle {
            get {
                return ResourceManager.GetString("TriggersView_PropertyTriggerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бесплатно.
        /// </summary>
        internal static string TriggersView_Status_Free {
            get {
                return ResourceManager.GetString("TriggersView_Status_Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обычный.
        /// </summary>
        internal static string TriggersView_Status_Normal {
            get {
                return ResourceManager.GetString("TriggersView_Status_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет в наличии.
        /// </summary>
        internal static string TriggersView_Status_NotAvailable {
            get {
                return ResourceManager.GetString("TriggersView_Status_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Премиум.
        /// </summary>
        internal static string TriggersView_Status_Premium {
            get {
                return ResourceManager.GetString("TriggersView_Status_Premium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Триггеры позволяют изменять внешний вид элементов при выполнении определенных условий.
        /// </summary>
        internal static string TriggersView_Subtitle {
            get {
                return ResourceManager.GetString("TriggersView_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DataTrigger.
        /// </summary>
        internal static string TriggersView_Summary_DataTrigger {
            get {
                return ResourceManager.GetString("TriggersView_Summary_DataTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реагирует на изменения в данных (привязка к модели).
        /// </summary>
        internal static string TriggersView_Summary_DataTriggerDescription {
            get {
                return ResourceManager.GetString("TriggersView_Summary_DataTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EventTrigger.
        /// </summary>
        internal static string TriggersView_Summary_EventTrigger {
            get {
                return ResourceManager.GetString("TriggersView_Summary_EventTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запускает анимацию при событии (Click, Loaded и др.).
        /// </summary>
        internal static string TriggersView_Summary_EventTriggerDescription {
            get {
                return ResourceManager.GetString("TriggersView_Summary_EventTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MultiTrigger.
        /// </summary>
        internal static string TriggersView_Summary_MultiTrigger {
            get {
                return ResourceManager.GetString("TriggersView_Summary_MultiTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Срабатывает при выполнении нескольких условий.
        /// </summary>
        internal static string TriggersView_Summary_MultiTriggerDescription {
            get {
                return ResourceManager.GetString("TriggersView_Summary_MultiTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PropertyTrigger.
        /// </summary>
        internal static string TriggersView_Summary_PropertyTrigger {
            get {
                return ResourceManager.GetString("TriggersView_Summary_PropertyTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реагирует на свойства элемента (IsMouseOver, IsFocused и др.).
        /// </summary>
        internal static string TriggersView_Summary_PropertyTriggerDescription {
            get {
                return ResourceManager.GetString("TriggersView_Summary_PropertyTriggerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📊 Сводка по триггерам:.
        /// </summary>
        internal static string TriggersView_SummaryTitle {
            get {
                return ResourceManager.GetString("TriggersView_SummaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⚡ Триггеры в WPF.
        /// </summary>
        internal static string TriggersView_Title {
            get {
                return ResourceManager.GetString("TriggersView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Двусторонняя привязка: изменения в любом поле обновляют все связанные элементы.
        /// </summary>
        internal static string TwoWayBindingView_Description {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 ПРИМЕР 1: Два текстбокса связаны с одним свойством.
        /// </summary>
        internal static string TwoWayBindingView_Example1_Title {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Example1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 ПРИМЕР 2: Слайдер и текстбокс для цены.
        /// </summary>
        internal static string TwoWayBindingView_Example2_Title {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Example2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 ПРИМЕР 3: CheckBox управляет видимостью.
        /// </summary>
        internal static string TwoWayBindingView_Example3_Title {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Example3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 ПРИМЕР 4: Изменение данных в коде.
        /// </summary>
        internal static string TwoWayBindingView_Example4_Title {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Example4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в интерфейсе → обновляют модель.
        /// </summary>
        internal static string TwoWayBindingView_ExplanationBullet1 {
            get {
                return ResourceManager.GetString("TwoWayBindingView_ExplanationBullet1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Изменения в модели (кнопки) → обновляют интерфейс.
        /// </summary>
        internal static string TwoWayBindingView_ExplanationBullet2 {
            get {
                return ResourceManager.GetString("TwoWayBindingView_ExplanationBullet2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на • Все элементы синхронизированы между собой.
        /// </summary>
        internal static string TwoWayBindingView_ExplanationBullet3 {
            get {
                return ResourceManager.GetString("TwoWayBindingView_ExplanationBullet3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 📌 Что демонстрирует TwoWay привязка:.
        /// </summary>
        internal static string TwoWayBindingView_ExplanationTitle {
            get {
                return ResourceManager.GetString("TwoWayBindingView_ExplanationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Это дополнительная информация, которая появляется/скрывается по чекбоксу.
        /// </summary>
        internal static string TwoWayBindingView_ExtraInfoText {
            get {
                return ResourceManager.GetString("TwoWayBindingView_ExtraInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название товара (редактируй любое поле):.
        /// </summary>
        internal static string TwoWayBindingView_Label_ProductNameEditAnyField {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Label_ProductNameEditAnyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена (двигай слайдер или вводи число):.
        /// </summary>
        internal static string TwoWayBindingView_PriceInstruction {
            get {
                return ResourceManager.GetString("TwoWayBindingView_PriceInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать дополнительную информацию.
        /// </summary>
        internal static string TwoWayBindingView_ShowExtraInfoLabel {
            get {
                return ResourceManager.GetString("TwoWayBindingView_ShowExtraInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 🔄 Двухсторонняя привязка (TwoWay).
        /// </summary>
        internal static string TwoWayBindingView_Title {
            get {
                return ResourceManager.GetString("TwoWayBindingView_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ⬆️ Изменяй текст в любом поле — второй обновляется сразу.
        /// </summary>
        internal static string TwoWayBindingView_UpHintText {
            get {
                return ResourceManager.GetString("TwoWayBindingView_UpHintText", resourceCulture);
            }
        }
    }
}
